### ISSUE TITLE
by_rel("next") is returning nil

### ISSUE THREAD

**Issue by nikolalsvk** [alexpeattie/nitlink#2]
It seems I cannot fetch proper Nitlink::Link object, I get nil when I do `links.by_rel("next")`

Here's the debugging I did:
```
[#<struct Nitlink::Link target=#<URI::HTTPS URL>, relation_type="'next'", context=#<URI::HTTPS URL>, target_attributes={}>, 
#<struct Nitlink::Link target=#<URI::HTTPS some URL>, relation_type="'last'", context=#<URI::HTTPS Some URL>, target_attributes={}>]
(byebug) links.by_rel("next")
nil
(byebug) links.by_rel('next')
nil
```

It probably has to do with the relation type being `'next'` instead of `next`

**Comment by alexpeattie** [comment]
Can you post the Link header you're parsing to generate `links`? I suspect it might be something like:

```
<https://api.github.com/search/code?q=addClass+user%3Amozilla&page=2>; rel='next'
```

rather than the correct form with double quotes:

```
<https://api.github.com/search/code?q=addClass+user%3Amozilla&page=2>; rel="next"
```

Relation types can't be single-quoted, or more technically, if they are then the correct value is the literal string `'next'`. You shouldn't ever come across single-quoted relation types in the wild though 🙈! (Unless a server has been misconfigured).

**Comment by nikolalsvk** [comment]
Sure, here's the header:

```
Link:
  - <https://api.github.com/marketplace_purchases?page=1&per_page=100>; rel='next',
    <https://api.github.com/marketplace_purchases?page=1&per_page=100>; rel='last'
```

It's what you suspected. To be honest, I did some mocking of the Link header for VCR cassette, and I put those single quoted strings. I'll remove them since they cannot be met in the wild.

I'll change it to double quotes, thanks for the help!
